In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Student_Performance_New.csv')

In [4]:
df.head()

,student_id,gender,math_score,science_score,english_score,overall_score,final_grade
0,1,male,42.7,55.4,57.0,53.1,e
1,2,female,57.6,68.8,64.8,61.3,d
2,3,female,84.8,95.0,79.2,89.6,b
3,4,other,44.4,27.5,54.7,41.6,e
4,5,female,8.9,32.7,30.0,25.4,f

In [5]:
df = df.dropna()

In [7]:
df

,student_id,gender,math_score,science_score,english_score,overall_score,final_grade
0,1,male,42.7,55.4,57.0,53.1,e
1,2,female,57.6,68.8,64.8,61.3,d
2,3,female,84.8,95.0,79.2,89.6,b
3,4,other,44.4,27.5,54.7,41.6,e
4,5,female,8.9,32.7,30.0,25.4,f
...,...,...,...,...,...,...,...
24995,12047,female,55.8,48.5,46.7,46.1,e
24996,1102,female,64.8,48.2,52.3,56.5,d
24997,4422,other,50.5,20.3,36.1,36.7,f
24998,7858,male,13.0,34.2,7.3,34.1,f
24999,11621,other,36.5,45.1,16.5,31.4,f

In [9]:
df.columns

Index(['student_id', 'gender', 'math_score', 'science_score', 'english_score',
       'overall_score', 'final_grade'],
      dtype='object')

In [10]:
df["pass_fail"] = df["overall_score"].apply(lambda x: 1 if x >= 40 else 0)

In [11]:
X = df[["gender", "math_score", "science_score", "english_score"]]
y = df["pass_fail"]

In [13]:
df["gender"] = df["gender"].map({
    "male": 0,
    "female": 1,
    "other": 2
})

In [14]:
print(df["gender"].isnull().sum())

0

In [16]:
print(X.isnull().sum())

gender           25000
math_score           0
science_score        0
english_score        0
dtype: int64

In [18]:
print(df["gender"].dtype)
print(df["gender"].head())

float64
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: gender, dtype: float64

In [19]:
df["gender"] = df["gender"].astype(str)
df["gender"] = df["gender"].str.strip().str.lower()

In [21]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Reload dataset
df = pd.read_csv("Student_Performance_New.csv")

# Clean + encode gender
df["gender"] = df["gender"].astype(str).str.strip().str.lower()
df["gender"] = df["gender"].map({
    "male": 0,
    "female": 1,
    "other": 2
})

# Target
df["pass_fail"] = df["overall_score"].apply(lambda x: 1 if x >= 40 else 0)

# Features
X = df[["gender", "math_score", "science_score", "english_score"]]
y = df["pass_fail"]

# Drop NaNs
X = X.dropna()
y = y.loc[X.index]

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train
model = LogisticRegression(max_iter=300)
model.fit(X_train, y_train)

# Evaluate
preds = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, preds))

Accuracy: 0.9462

In [22]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

preds = rf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, preds))

Accuracy: 0.9704

In [23]:
import joblib
joblib.dump(model, "student_performance_model.pkl")

['student_performance_model.pkl']

In [24]:
import joblib

model = joblib.load("student_performance_model.pkl")
print(model)

LogisticRegression(max_iter=300)

In [26]:
# gender: male=0, female=1, other=2
new_student = [[1, 70, 65, 72]]

prediction = model.predict(new_student)
if prediction[0] == 1:
    print("Prediction: Pass")
else:
    print("Prediction: Fail")

Prediction: Pass

c:\Users\adity\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [27]:
prob = model.predict_proba(new_student)
print("Probability [Fail, Pass]:", prob)

Probability [Fail, Pass]: [[1.65667814e-04 9.99834332e-01]]

c:\Users\adity\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(